import type { ClassType } from '../types';

/**
 * Per-dungeon-run secondary resources. Generated by combat events
 * (offensive abilities), consumed by spend abilities, reset on dungeon exit.
 *
 * Mage has neither — both fields stay 0 and are simply unused.
 */
export interface SecondaryResources {
  rage: number;
  faith: number;
}

export const RAGE_MAX = 12;
export const FAITH_MAX = 12;

export function emptySecondaryResources(): SecondaryResources {
  return { rage: 0, faith: 0 };
}

export function resetSecondaryResources(): SecondaryResources {
  return emptySecondaryResources();
}

export function gainRage(state: SecondaryResources, amount: number): SecondaryResources {
  return { ...state, rage: Math.max(0, Math.min(RAGE_MAX, state.rage + amount)) };
}

export function spendRage(state: SecondaryResources, amount: number): SecondaryResources {
  if (state.rage < amount) {
    throw new Error(`Cannot spend ${amount} rage (have ${state.rage})`);
  }
  return { ...state, rage: state.rage - amount };
}

export function gainFaith(state: SecondaryResources, amount: number): SecondaryResources {
  return { ...state, faith: Math.max(0, Math.min(FAITH_MAX, state.faith + amount)) };
}

export function spendFaith(state: SecondaryResources, amount: number): SecondaryResources {
  if (state.faith < amount) {
    throw new Error(`Cannot spend ${amount} faith (have ${state.faith})`);
  }
  return { ...state, faith: state.faith - amount };
}

export function canAffordSecondary(
  state: SecondaryResources,
  classType: ClassType,
  cost: number | undefined,
): boolean {
  if (!cost) return true;
  if (classType === 'warrior') return state.rage >= cost;
  if (classType === 'priest') return state.faith >= cost;
  return false;
}

export function spendSecondary(
  state: SecondaryResources,
  classType: ClassType,
  cost: number | undefined,
): SecondaryResources {
  if (!cost) return state;
  if (classType === 'warrior') return spendRage(state, cost);
  if (classType === 'priest') return spendFaith(state, cost);
  throw new Error(`Class ${classType} has no secondary resource to spend`);
}

export function gainSecondary(
  state: SecondaryResources,
  classType: ClassType,
  amount: number | undefined,
): SecondaryResources {
  if (!amount) return state;
  if (classType === 'warrior') return gainRage(state, amount);
  if (classType === 'priest') return gainFaith(state, amount);
  return state;
}
