export interface VocabEntry {
  jp: string;
  romaji: string;
  en: string;
}

export const VOCAB_POOL: VocabEntry[] = [
  { jp: '水', romaji: 'mizu', en: 'water' },
  { jp: '火', romaji: 'hi', en: 'fire' },
  { jp: '木', romaji: 'ki', en: 'tree' },
  { jp: '山', romaji: 'yama', en: 'mountain' },
  { jp: '川', romaji: 'kawa', en: 'river' },
  { jp: '空', romaji: 'sora', en: 'sky' },
  { jp: '海', romaji: 'umi', en: 'sea' },
  { jp: '雨', romaji: 'ame', en: 'rain' },
  { jp: '雪', romaji: 'yuki', en: 'snow' },
  { jp: '風', romaji: 'kaze', en: 'wind' },
  { jp: '日', romaji: 'hi', en: 'sun' },
  { jp: '月', romaji: 'tsuki', en: 'moon' },
  { jp: '星', romaji: 'hoshi', en: 'star' },
  { jp: '花', romaji: 'hana', en: 'flower' },
  { jp: '草', romaji: 'kusa', en: 'grass' },
  { jp: '石', romaji: 'ishi', en: 'stone' },
  { jp: '土', romaji: 'tsuchi', en: 'earth' },
  { jp: '金', romaji: 'kin', en: 'gold' },
  { jp: '銀', romaji: 'gin', en: 'silver' },
  { jp: '鉄', romaji: 'tetsu', en: 'iron' },
  { jp: '人', romaji: 'hito', en: 'person' },
  { jp: '男', romaji: 'otoko', en: 'man' },
  { jp: '女', romaji: 'onna', en: 'woman' },
  { jp: '子', romaji: 'ko', en: 'child' },
  { jp: '父', romaji: 'chichi', en: 'father' },
  { jp: '母', romaji: 'haha', en: 'mother' },
  { jp: '兄', romaji: 'ani', en: 'older brother' },
  { jp: '姉', romaji: 'ane', en: 'older sister' },
  { jp: '弟', romaji: 'otouto', en: 'younger brother' },
  { jp: '妹', romaji: 'imouto', en: 'younger sister' },
  { jp: '友', romaji: 'tomo', en: 'friend' },
  { jp: '先生', romaji: 'sensei', en: 'teacher' },
  { jp: '学生', romaji: 'gakusei', en: 'student' },
  { jp: '学校', romaji: 'gakkou', en: 'school' },
  { jp: '本', romaji: 'hon', en: 'book' },
  { jp: '紙', romaji: 'kami', en: 'paper' },
  { jp: '机', romaji: 'tsukue', en: 'desk' },
  { jp: '椅子', romaji: 'isu', en: 'chair' },
  { jp: '家', romaji: 'ie', en: 'house' },
  { jp: '部屋', romaji: 'heya', en: 'room' },
  { jp: '門', romaji: 'mon', en: 'gate' },
  { jp: '窓', romaji: 'mado', en: 'window' },
  { jp: '道', romaji: 'michi', en: 'road' },
  { jp: '町', romaji: 'machi', en: 'town' },
  { jp: '国', romaji: 'kuni', en: 'country' },
  { jp: '駅', romaji: 'eki', en: 'station' },
  { jp: '車', romaji: 'kuruma', en: 'car' },
  { jp: '電車', romaji: 'densha', en: 'train' },
  { jp: '自転車', romaji: 'jitensha', en: 'bicycle' },
  { jp: '飛行機', romaji: 'hikouki', en: 'airplane' },
  { jp: '犬', romaji: 'inu', en: 'dog' },
  { jp: '猫', romaji: 'neko', en: 'cat' },
  { jp: '鳥', romaji: 'tori', en: 'bird' },
  { jp: '魚', romaji: 'sakana', en: 'fish' },
  { jp: '馬', romaji: 'uma', en: 'horse' },
  { jp: '牛', romaji: 'ushi', en: 'cow' },
  { jp: '豚', romaji: 'buta', en: 'pig' },
  { jp: '虫', romaji: 'mushi', en: 'insect' },
  { jp: '米', romaji: 'kome', en: 'rice' },
  { jp: 'パン', romaji: 'pan', en: 'bread' },
  { jp: '肉', romaji: 'niku', en: 'meat' },
  { jp: '野菜', romaji: 'yasai', en: 'vegetable' },
  { jp: '果物', romaji: 'kudamono', en: 'fruit' },
  { jp: '茶', romaji: 'cha', en: 'tea' },
  { jp: '酒', romaji: 'sake', en: 'alcohol' },
  { jp: '塩', romaji: 'shio', en: 'salt' },
  { jp: '砂糖', romaji: 'satou', en: 'sugar' },
  { jp: '卵', romaji: 'tamago', en: 'egg' },
  { jp: '牛乳', romaji: 'gyuunyuu', en: 'milk' },
  { jp: '朝', romaji: 'asa', en: 'morning' },
  { jp: '昼', romaji: 'hiru', en: 'noon' },
  { jp: '夜', romaji: 'yoru', en: 'night' },
  { jp: '今日', romaji: 'kyou', en: 'today' },
  { jp: '明日', romaji: 'ashita', en: 'tomorrow' },
  { jp: '昨日', romaji: 'kinou', en: 'yesterday' },
  { jp: '週', romaji: 'shuu', en: 'week' },
  { jp: '月曜日', romaji: 'getsuyoubi', en: 'Monday' },
  { jp: '火曜日', romaji: 'kayoubi', en: 'Tuesday' },
  { jp: '春', romaji: 'haru', en: 'spring' },
  { jp: '夏', romaji: 'natsu', en: 'summer' },
  { jp: '秋', romaji: 'aki', en: 'autumn' },
  { jp: '冬', romaji: 'fuyu', en: 'winter' },
  { jp: '一', romaji: 'ichi', en: 'one' },
  { jp: '二', romaji: 'ni', en: 'two' },
  { jp: '三', romaji: 'san', en: 'three' },
  { jp: '四', romaji: 'shi', en: 'four' },
  { jp: '五', romaji: 'go', en: 'five' },
  { jp: '六', romaji: 'roku', en: 'six' },
  { jp: '七', romaji: 'shichi', en: 'seven' },
  { jp: '八', romaji: 'hachi', en: 'eight' },
  { jp: '九', romaji: 'kyuu', en: 'nine' },
  { jp: '十', romaji: 'juu', en: 'ten' },
  { jp: '百', romaji: 'hyaku', en: 'hundred' },
  { jp: '千', romaji: 'sen', en: 'thousand' },
  { jp: '大きい', romaji: 'ookii', en: 'big' },
  { jp: '小さい', romaji: 'chiisai', en: 'small' },
  { jp: '高い', romaji: 'takai', en: 'tall' },
  { jp: '安い', romaji: 'yasui', en: 'cheap' },
  { jp: '新しい', romaji: 'atarashii', en: 'new' },
  { jp: '古い', romaji: 'furui', en: 'old' },
  { jp: '良い', romaji: 'yoi', en: 'good' },
  { jp: '悪い', romaji: 'warui', en: 'bad' },
  { jp: '行く', romaji: 'iku', en: 'to go' },
  { jp: '来る', romaji: 'kuru', en: 'to come' },
  { jp: '見る', romaji: 'miru', en: 'to see' },
  { jp: '聞く', romaji: 'kiku', en: 'to listen' },
  { jp: '話す', romaji: 'hanasu', en: 'to speak' },
  { jp: '食べる', romaji: 'taberu', en: 'to eat' },
  { jp: '飲む', romaji: 'nomu', en: 'to drink' },
];
