/**
 * Grammar spine generator -- DoD C / slice C (grammar follow-up).
 *
 * Build/test-time ONLY (imports `grammar-list.ts`, which reads `data/vendor/`
 * via `node:fs`; never bundled into the client).
 *
 * Grammar is the one category with **no dictionary gate** — JMdict/KANJIDIC2
 * cover words and kanji, not patterns. So the blessed grammar list is the sole
 * authority for both membership AND content (`grammar-list.ts`), and the only
 * correctness guard is that every entry renders as a **deterministically-gradable
 * MCQ**: a `recall` face (show the JP grammar point, pick its English meaning).
 * We do NOT author cloze sentences here — the source carries none, and inventing
 * them would both break determinism and violate "no invented curriculum".
 *
 * Run it (regenerate `grammar.md`) with:
 *   GEN_GRAMMAR=1 npx vite-node src/content/spine/generate-grammar.ts
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { readGrammarList, type GrammarRow } from './grammar-list';
import type { JlptLevel } from './blessed';

export interface GeneratedGrammar {
  id: string;
  jp: string;
  reading: string;
  en: string;
  jlpt: JlptLevel;
}

export interface GrammarGenResult {
  entries: GeneratedGrammar[];
}

/**
 * id = `g:${level}-${num}`. The source `#` is unique and contiguous within each
 * level, so this is stable and unique — and it keeps the six grammar points that
 * share a JP form but differ in meaning (N5 でも "but" vs N4 でも "…or something")
 * as the distinct curriculum items they are, rather than collapsing them.
 */
function idOf(row: GrammarRow): string {
  return `g:${row.level}-${row.num}`;
}

export function generateGrammar(): GrammarGenResult {
  const entries: GeneratedGrammar[] = [];
  const rows = readGrammarList();
  // N5 before N4 so the spine reads low-to-high level.
  rows.sort((a, b) =>
    a.level === b.level ? a.num - b.num : a.level === 'N5' ? -1 : 1,
  );
  for (const row of rows) {
    entries.push({
      id: idOf(row),
      jp: row.jp,
      reading: row.romaji,
      en: row.meaning,
      jlpt: row.level,
    });
  }
  return { entries };
}

// --- markdown emission ---------------------------------------------------------

const HEADER = `<!--
  Grammar spine. GENERATED by src/content/spine/generate-grammar.ts from the
  blessed JLPT grammar list (data/vendor/grammar/), filtered to N5/N4.
  Do not hand-edit; re-run the generator instead:
    GEN_GRAMMAR=1 npx vite-node src/content/spine/generate-grammar.ts
  Grammar has no dictionary gate (JMdict/KANJIDIC2 are words/kanji); the list is
  the sole authority for membership AND content. The only correctness guard is
  deterministic gradability: a single recall (JP->en) MCQ face. No cloze faces
  are authored — the source carries no sentences and inventing them is barred.
-->
`;

function scalar(v: string): string {
  return v.replace(/\s+/g, ' ').trim();
}

export function renderGrammarMarkdown(entries: readonly GeneratedGrammar[]): string {
  const blocks = entries.map(
    (e) => `---
id: ${scalar(e.id)}
type: grammar
jp: ${scalar(e.jp)}
reading: ${scalar(e.reading)}
en: ${scalar(e.en)}
pos: grammar
jlpt: ${e.jlpt}
tags: []
faces: [recall]
---`,
  );
  return HEADER + '\n' + blocks.join('\n\n') + '\n';
}

// --- runner --------------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, 'grammar.md');

function main(): void {
  const { entries } = generateGrammar();
  writeFileSync(OUT, renderGrammarMarkdown(entries), 'utf8');
  const n5 = entries.filter((e) => e.jlpt === 'N5').length;
  const n4 = entries.filter((e) => e.jlpt === 'N4').length;
  console.log(`wrote ${entries.length} grammar entries (N5 ${n5}, N4 ${n4}) -> ${OUT}`);
}

// Importers (the coverage test) must not trigger file I/O. vite-node masks
// argv[1], so gate emission behind an env flag (mirrors generate-vocab.ts).
if (process.env.GEN_GRAMMAR === '1') {
  main();
}
