/**
 * Kanji spine generator -- DoD C / slice C (kanji follow-up).
 *
 * Build/test-time ONLY (imports `kanjidic.ts` + `kanji-membership.ts`, both of
 * which read `data/vendor/` from disk via `node:fs`; never bundled into the
 * client).
 *
 * Membership comes from the blessed JLPT N5/N4 kanji lists
 * (`kanji-membership.ts`); correctness (readings + meanings) comes from the
 * vendored KANJIDIC2 (`kanjidic.ts`). For each blessed kanji we *derive* its
 * primary reading (first kun-yomi, else first on-yomi) and primary meaning
 * (first English gloss) from the dictionary. Nothing here invents curriculum: a
 * kanji absent from KANJIDIC2 becomes a residual, never a guess.
 *
 * Run it (regenerate `kanji.md`) with:
 *   GEN_KANJI=1 npx vite-node src/content/spine/generate-kanji.ts
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  loadKanjidicIndex,
  lookupKanji,
  primaryReading,
  type KanjidicIndex,
} from './kanjidic';
import { readKanjiList } from './kanji-membership';
import type { JlptLevel } from './blessed';

export interface GeneratedKanji {
  id: string;
  jp: string;
  reading: string;
  en: string;
  jlpt: JlptLevel;
}

export interface KanjiGenResult {
  entries: GeneratedKanji[];
  /** Kanji that resolved but were already emitted at a lower level (kept once). */
  duplicates: { char: string; level: JlptLevel; id: string }[];
  /** Kanji that did not resolve against KANJIDIC2 (missing char / no reading). */
  residuals: { char: string; level: JlptLevel }[];
}

export function generateKanji(
  index: KanjidicIndex = loadKanjidicIndex(),
): KanjiGenResult {
  const entries: GeneratedKanji[] = [];
  const duplicates: KanjiGenResult['duplicates'] = [];
  const residuals: KanjiGenResult['residuals'] = [];
  const seen = new Set<string>();

  // N5 first so a kanji shared across levels is tagged at the lower level.
  for (const level of ['N5', 'N4'] as const) {
    for (const char of readKanjiList(level)) {
      const info = lookupKanji(index, char);
      const reading = info ? primaryReading(info) : null;
      const en = info?.meanings[0] ?? null;
      if (!info || !reading || !en) {
        residuals.push({ char, level });
        continue;
      }
      const id = `k:${char}`;
      if (seen.has(id)) {
        duplicates.push({ char, level, id });
        continue;
      }
      seen.add(id);
      entries.push({ id, jp: char, reading, en, jlpt: level });
    }
  }
  return { entries, duplicates, residuals };
}

// --- markdown emission ---------------------------------------------------------

const HEADER = `<!--
  Kanji spine. GENERATED by src/content/spine/generate-kanji.ts from the blessed
  JLPT N5/N4 kanji lists (data/vendor/kanji/), gated against vendored KANJIDIC2.
  Do not hand-edit; re-run the generator instead:
    GEN_KANJI=1 npx vite-node src/content/spine/generate-kanji.ts
  reading = first kun-yomi (else first on-yomi); en = KANJIDIC2's first gloss.
  Faces: meaning (kanji->en) + reading (kanji->kana), both deterministic MCQ.
  KANJIDIC2 (c) EDRDG, used under the EDRDG Licence (CC BY-SA 4.0).
-->
`;

function scalar(v: string): string {
  return v.replace(/\s+/g, ' ').trim();
}

export function renderKanjiMarkdown(entries: readonly GeneratedKanji[]): string {
  const blocks = entries.map(
    (e) => `---
id: ${scalar(e.id)}
type: kanji
jp: ${scalar(e.jp)}
reading: ${scalar(e.reading)}
en: ${scalar(e.en)}
pos: kanji
jlpt: ${e.jlpt}
tags: []
faces: [meaning, reading]
---`,
  );
  return HEADER + '\n' + blocks.join('\n\n') + '\n';
}

// --- runner --------------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, 'kanji.md');

function main(): void {
  const { entries, duplicates, residuals } = generateKanji();
  writeFileSync(OUT, renderKanjiMarkdown(entries), 'utf8');
  const n5 = entries.filter((e) => e.jlpt === 'N5').length;
  const n4 = entries.filter((e) => e.jlpt === 'N4').length;
  console.log(`wrote ${entries.length} kanji (N5 ${n5}, N4 ${n4}) -> ${OUT}`);
  console.log(`  duplicates skipped: ${duplicates.length}`);
  console.log(`  residuals (unresolved): ${residuals.length}`);
  for (const r of residuals) console.log(`    RESIDUAL ${r.level}  ${r.char}`);
}

// Importers (the coverage test) must not trigger file I/O. vite-node masks
// argv[1], so gate emission behind an env flag (mirrors generate-vocab.ts).
if (process.env.GEN_KANJI === '1') {
  main();
}
